---
substitutions:
  id_prefix: ratgdo32
  friendly_name: "ratgdo32"
  # Hardware UART2 for DevKit V1
  uart_tx_pin: GPIO17
  uart_rx_pin: GPIO16
  input_obst_pin: GPIO19
  # Safety "Dummy" pins to satisfy component requirements
  status_door_pin: GPIO26
  status_obstruction_pin: GPIO25
  dry_contact_open_pin: GPIO13
  dry_contact_close_pin: GPIO14
  dry_contact_light_pin: GPIO27

web_server:
  local: true

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  min_version: 2026.4.0
  project:
    name: eborchardt.esp32dev_ratgdo
    version: "1.0"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# This allows the ESPHome dashboard to track updates to this file
dashboard_import:
  package_import_url: github://eborchardt/esphome-ratgdo/static/esp32dev.yaml@main

packages:
  remote_package:
    url: https://github.com/eborchardt/esphome-ratgdo
    ref: main
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

improv_serial:

esp32_improv:
  authorizer: none

wifi:
  ap:
    ssid: "ratgdo32-fallback"

captive_portal:

logger:
  level: DEBUG
